# Generated by Django 5.1.3 on 2024-11-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPY', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='is_complete',
        ),
        migrations.RemoveField(
            model_name='target',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='mission',
            name='name',
            field=models.CharField(default='Default Mission', max_length=255),
        ),
        migrations.AddField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20),
        ),
        migrations.AddField(
            model_name='target',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='spycat',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='spycat',
            name='years_of_experience',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='target',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='target',
            name='notes',
            field=models.TextField(blank=True, default='No notes available'),
        ),
    ]
